### PR TITLE
Add clang 11 upgrade information to README

### PR DESCRIPTION
**Pull request by kkjeer**
Update the "source code update" section to reference the latest upgrade to clang 11 rather than the previous upgrade to clang 9.

### CODE REVIEW

**Review by sulekhark — APPROVED** [review]
LGTM. Thank you for all your efforts to make this happen!

**Comment by mgrang** [comment]
I suggest we don't overwrite the existing source code update info. This would be helpful in preserving the history of our upgrades. We may decide to move the source upgrade info to its own file and simply have a pointer to it on the checkedc-clang wiki.

**Comment by kkjeer** [comment]
> I suggest we don't overwrite the existing source code update info. This would be helpful in preserving the history of our upgrades. We may decide to move the source upgrade info to its own file and simply have a pointer to it on the checkedc-clang wiki.

I added the clang 9 upgrade information back to the README. On a related note, the link in the document for clang 9 (http://llvm.org/viewvc/llvm-project?view=revision&revision=366428) results in a 404 - is there a different link we can use?

**Review by sulekhark — APPROVED** [review]
LGTM.

**Review by mgrang — APPROVED** [review]

**Pull request merged**
